apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-go-sample-multi-component-example-main-hwkx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-go-sample-multi-component-example-main-hwkx
    app.kubernetes.io/part-of: multi-component-application
  name: devfile-go-sample-multi-component-example-main-hwkx
  namespace: e2e-demo-izdo
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: devfile-go-sample-multi-component-example-main-hwkx
    weight: 100
status: {}
